### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by YorickBM** [KasperFranz/BetterChunkLoader#17]
Please help me men i donwloaded your plugin that latest version put it in to my server started it up stoped the server configured everyting right and it is just giving a error when it wants to load the configurtion in!

**Comment by KasperFranz** [comment]
What errors do you get? 

post a stacktrace :)

**Comment by YorickBM** [comment]
okay give me a second :)

**Comment by YorickBM** [comment]
`[15:42:02] [Server thread/INFO] [Woot]: LootTableManager: Load loot statistics from C:\Users\yorick\Desktop\beyond\woot\loot.json
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]: java.io.IOException: configurate.typesafe.config.ConfigException$Parse: Reader: 17: Expecting close brace } or a comma, got '=' (if you intended '=' to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at ninja.leaping.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:171)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at ninja.leaping.configurate.loader.ConfigurationLoader.load(ConfigurationLoader.java:42)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at net.kaikk.mc.bcl.config.Config.load(Config.java:54)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at net.kaikk.mc.bcl.config.Config.setup(Config.java:46)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at net.kaikk.mc.bcl.BetterChunkLoader.onServerStart(BetterChunkLoader.java:77)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at org.spongepowered.common.event.listener.GameStartedServerEventListener_BetterChunkLoader_onServerStart1.handle(Unknown Source)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:342)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:234)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at java.lang.reflect.Method.invoke(Unknown Source)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at java.lang.reflect.Method.invoke(Unknown Source)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzb000(LoadController.java:552)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:868)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:297)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:433)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.config.Config:load:58]:     at java.lang.Thread.run(Unknown Source)
[15:42:03] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: configurate.typesafe.config.ConfigException$Parse: Reader: 17: Expecting close brace } or a comma, got '=' (if you intended '=' to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
[15:42:03] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
[15:42:03] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
[15:42:03] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:475)
[15:42:03] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:247)
[15:42:03] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:405)
[15:42:03] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:595)
[15:42:03] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at configurate.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
[15:42:03] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at configurate.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260)
[15:42:03] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at configurate.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248)
[15:42:03] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at configurate.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
[15:42:03] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at configurate.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
[15:42:03] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at configurate.typesafe.config.impl.Parseable.parse(Parseable.java:299)
[15:42:03] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at configurate.typesafe.config.ConfigFactory.parseReader(ConfigFactory.java:668)
[15:42:03] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at ninja.leaping.configurate.hocon.HoconConfigurationLoader.loadInternal(HoconConfigurationLoader.java:104)
[15:42:03] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at ninja.leaping.configurate.hocon.HoconConfigurationLoader.loadInternal(HoconConfigurationLoader.java:54)
[15:42:03] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at ninja.leaping.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:163)
[15:42:03] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     ... 35 more
[15:42:03] [Server thread/INFO] [betterchunkloader]: Loading config...
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]: java.lang.NullPointerException
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at net.kaikk.mc.bcl.BetterChunkLoader.onServerStart(BetterChunkLoader.java:85)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at org.spongepowered.common.event.listener.GameStartedServerEventListener_BetterChunkLoader_onServerStart1.handle(Unknown Source)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:342)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:234)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at java.lang.reflect.Method.invoke(Unknown Source)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at java.lang.reflect.Method.invoke(Unknown Source)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzb000(LoadController.java:552)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:868)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:297)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:433)
[15:42:03] [Server thread/INFO] [STDERR]: [net.kaikk.mc.bcl.BetterChunkLoader:onServerStart:114]:   at java.lang.Thread.run(Unknown Source)
[15:42:03] [Server thread/ERROR] [betterchunkloader]: Load failed!
[15:42:03] [Server thread/INFO] [FTBLib]: Reloaded SERVER on packmode 'default'`

**Comment by KasperFranz** [comment]
Put your config on a gist since that is what you have an error in

**Comment by YorickBM** [comment]
# Currently the only DataStore...
DataStore=MySQL
DefaultChunksAmount {
    Personal=0
    World=0
}
MaxChunksAmount {
    Personal=250
    World=250
}
# Time in hours before player's chunkloaders become inactive.
MaxHoursOffline=72
MySQL {
    Database=chunkloaders
    Hostname=localhost
    Password=
    Username=root 
}
# Unique name of server
ServerName=Beyond

Thats my Config My DataBase doesn't has any Password

**Comment by KasperFranz** [comment]
Does your mysql password contains any = ?

**Comment by YorickBM** [comment]
No my Mysql hasn't got a password

**Comment by KasperFranz** [comment]
try to put Password="" then

**Comment by YorickBM** [comment]
okay i will try

**Comment by YorickBM** [comment]
OMG THX MEN it wokrs now :)

**Comment by YorickBM** [comment]
Are the iron block always online or just online only?

**Comment by tolly765** [comment]
The iron blocks are online only
