### ISSUE TITLE
DB Connection is established on the main thread

### ISSUE THREAD

**Issue by clienthax** [KasperFranz/BetterChunkLoader#33]
Should ideally be on its own thread so it doesn't block the server thread
```
Stall report from 2020-05-23 17:27:31 +0100, 105 threads, stalled for at least 30000 ms.
Thread dump #1 for stall #1.
Heap memory usage: 18224 / 25769 MB (max. 25769 MB).
Created by sampler 1.84 (MC 1.12).

"Server thread" #40 prio=5
RUNNABLE
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	- locked java.net.SocksSocketImpl@13c277f6
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:250)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:512)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1341)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:634)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)
	at org.mariadb.jdbc.Driver.connect(Driver.java:89)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at net.kaikk.mc.bcl.datastore.MySqlDataStore.refreshConnection(MySqlDataStore.java:258)
	at net.kaikk.mc.bcl.datastore.MySqlDataStore.load(MySqlDataStore.java:50)
	at net.kaikk.mc.bcl.BetterChunkLoader.onServerStart(BetterChunkLoader.java:152)
	at org.spongepowered.common.event.listener.GameStartedServerEventListener_BetterChunkLoader_onServerStart37.handle(Unknown Source)
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:381)
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:456)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:417)
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:259)
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:377)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	- locked com.google.common.eventbus.Subscriber$SynchronizedSubscriber@e9b998bf
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	- locked com.google.common.eventbus.Subscriber$SynchronizedSubscriber@f3834092
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$zza000$forgeImpl$PostEvent(LoadController.java:568)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:804)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:302)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:488)
	at java.lang.Thread.run(Thread.java:813)

```

**Comment by KasperFranz** [comment]
This has been added in the code - would be good if you can try it out :)
