### ISSUE TITLE
cannot get blc to work

### ISSUE THREAD

**Issue by Chaosx911** [KasperFranz/BetterChunkLoader#50]
**What is the bug?**

Error occurred while executing command 'bcl bal' for source EntityPlayerMP['Chaos911'/244, l='world', x=2375.92, y=16.00, z=673.70]: null
Console 20:34:07
java.lang.NullPointerException: null
at net.kaikk.mc.bcl.datastore.AHashMapDataStore.getPlayerData(AHashMapDataStore.java:172) ~[AHashMapDataStore.class:?]
at net.kaikk.mc.bcl.datastore.AHashMapDataStore.getAlwaysOnFreeChunksAmount(AHashMapDataStore.java:118) ~[AHashMapDataStore.class:?]
at net.kaikk.mc.bcl.commands.CmdBalance.chunksInfo(CmdBalance.java:41) ~[CmdBalance.class:?]
at net.kaikk.mc.bcl.commands.CmdBalance.execute(CmdBalance.java:30) ~[CmdBalance.class:?]
at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2838-7.3.0]
at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2838-7.3.0]
at org.spongepowered.common.command.SpongeCommandDispatcher.process(SpongeCommandDispatcher.java:355) ~[SpongeCommandDispatcher.class:1.12.2-2838-7.3.0]
at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:360) [SpongeCommandManager.class:1.12.2-2838-7.3.0]
at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:665) [dh.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:219) [PacketPhaseUtil.class:1.12.2-2838-7.3.0]
at net.minecraft.network.PacketThreadUtil$1.redirect$zlc000$impl$redirectToPhaseTracker(SourceFile:540) [hv$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_271]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_271]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:310) [SpongeImplHooks.class:1.12.2-2838-7.3.0]
at net.minecraft.server.MinecraftServer.redirect$zjg000$onRun(MinecraftServer.java:4682) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]

- **Sponge Version:**
- spongeforge-1.12.2-2838-7.3.0.jar
- **BetterChunkLoader Version:**
- BetterChunkLoader-3.8.1-S7.1.0.jar
- **BCLForgeLib Version:**
-bclforgelib-1.12.2-1.1.jar

It is vital to supply all version numbers.

**To Reproduce**
Steps to reproduce the behaviour:
just doesn't work on a fresh install giving issues

**Expected behaviour**
What did you expect to happen?

expected to be able to add chunk loaders to players and such

**Comment by KasperFranz** [comment]
3.8.1 contains a bug as mentioned on the header.
I will get 3.8.2 released this week
Please use the rc for now
https://github.com/KasperFranz/BetterChunkLoader/releases/tag/3.8.2-RC1
